/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig;

public class Blossom5WrapperClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Blossom5WrapperClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Blossom5WrapperClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        Blossom5WrapperJNI.delete_Blossom5WrapperClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void execute(int node_num, int edge_num) {
    Blossom5WrapperJNI.Blossom5WrapperClass_execute(swigCPtr, this, node_num, edge_num);
  }

  public void addEdge(int index1, int index2, int weight) {
    Blossom5WrapperJNI.Blossom5WrapperClass_addEdge(swigCPtr, this, index1, index2, weight);
  }

  public int returnMatch() {
    return Blossom5WrapperJNI.Blossom5WrapperClass_returnMatch(swigCPtr, this);
  }

  public void createArrays(int node_num, int edge_num) {
    Blossom5WrapperJNI.Blossom5WrapperClass_createArrays(swigCPtr, this, node_num, edge_num);
  }

  public Blossom5WrapperClass() {
    this(Blossom5WrapperJNI.new_Blossom5WrapperClass(), true);
  }

}
