/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package swig;

public class Blossom5WrapperJNI {
  public final static native void Blossom5WrapperClass_execute(long jarg1, Blossom5WrapperClass jarg1_, int jarg2, int jarg3);
  public final static native void Blossom5WrapperClass_addEdge(long jarg1, Blossom5WrapperClass jarg1_, int jarg2, int jarg3, int jarg4);
  public final static native int Blossom5WrapperClass_returnMatch(long jarg1, Blossom5WrapperClass jarg1_);
  public final static native void Blossom5WrapperClass_createArrays(long jarg1, Blossom5WrapperClass jarg1_, int jarg2, int jarg3);
  public final static native long new_Blossom5WrapperClass();
  public final static native void delete_Blossom5WrapperClass(long jarg1);
}
